### Log in first
POST {{host}}/auth/login?email={{email}}&password={{password}}
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"

}

> {%
client.test("Request executed successfully", function() {
   client.global.set("token", response.body["data"]);
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### Join in Club
POST {{host}}/clubs/join/5
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Invite members
POST {{host}}/clubs/invite/5
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_ids": "[5,6,7]"
}

### Leave club
POST {{host}}/clubs/leave/5
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json

### Remove member from Club
POST {{host}}/clubs/5/remove/7
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json

### Remove member from Club
POST {{host}}/clubs/5/accept/7
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json

### Remove member from Club
POST {{host}}/clubs/5/decline/6
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
Content-Type: application/json




