version: "3.4"

services:
  app:
    image: test.docker.og:5000/__PROJ__-php_prod:__TAG__
    networks:
      - backend
    volumes:
      - /nfs/storage1/__PROJ__/__BRANCH__/log/app/:/var/log/
      # logy pro automaticke sbirani do graylogu
      - /nfs/storage1/__PROJ__/__BRANCH__/log/laravel/:/var/www/html/storage/logs/gelf
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: __CONSTRAINTS__

  apache:
    image: test.docker.og:5000/__PROJ__-apache_prod:__TAG__
    networks:
      - backend
    ports:
      - __APACHE_PORT__:80
    volumes:
      - /nfs/storage1/__PROJ__/__BRANCH__/log/apache/:/var/log/
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: __CONSTRAINTS__

  db:
    image: percona/percona-server:8
    networks:
      - backend
    ports:
      - 9806:3306
    volumes:
      - /nfs/storage1/__PROJ__/__BRANCH__/volumes/mysql/:/var/lib/mysql
      - /nfs/storage1/__PROJ__/__BRANCH__/log/mysql/:/var/log/mysql
      - /nfs/storage1/__PROJ__/__BRANCH__/config/mysql/:/etc/my.cnf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass_danda
      - MYSQL_DATABASE=albi
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # superuser access for ssp_devel
      - MYSQL_USER=albi_hry
      - MYSQL_PASSWORD=albi_hry
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2.5G'
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: __CONSTRAINTS__

  proxy:
    image: jwilder/whoami
    networks:
      - routable
    deploy:
      labels:
        caddy: __URL__
        caddy.reverse_proxy: 10.255.254.40:__APACHE_PORT__
        caddy.tls: __TLS__
      placement:
        constraints:
          - node.role == manager

networks:
  backend:
    driver: overlay
  routable:
    external: true
